### ISSUE TITLE
redundant return in 2.20.scala

### ISSUE THREAD

**Issue by giabao** [handsonscala/handsonscala#22]
This line is redundant, may confuse readers:

https://github.com/handsonscala/handsonscala/blob/e39750b5407f0d69770b0ace239fc087aa5bc514/snippets/2.20.scala#L8

**Comment by lihaoyi** [comment]
@giabao that line makes `result` get printed when the test completes, giving you a mechanism to manually review and sanity check the test results. Not strictly necessary, but sometimes nice to have
