### ISSUE TITLE
PDF downloads as HTML file containing raw postscript

### ISSUE THREAD

**Issue by ghost** [handsonscala/handsonscala#29]
I just bought your book as PDF, but unfortunately it downloads with an ".html" extension and/or mime type so it opens to a page of raw postscript code on my iPad, which is really not very useful.  By downloading on a computer, and changing the extension manually, I could open the file and load it in to books. But really it would make life a lot easier if you could change this. 

Thanks!

**Comment by lihaoyi** [comment]
Not sure if this is within my control, the download is provided by the Gumroad payment provider :/
