### ISSUE TITLE
Installing Mill issue

### ISSUE THREAD

**Issue by livid16g** [handsonscala/handsonscala#34]
Hello - i am @ section 2.4 "Installing Mill". I have downloaded the example-3.zip package and unzipped it.

**Comment by livid16g** [comment]
However, when i do "./mill foo.compile", the download of mill is not happening and i am getting the following error(s):                            

(base) j00533938@lhrpbig100002:/sim_home/j00533938/github/example-3$ ./mill foo.compile
[1/25] mill.scalalib.ZincWorkerModule.compilerInterfaceClasspath | Downloading [2/2] artifacts (~0/0 bytes)
1 targets failed
mill.scalalib.ZincWorkerModule.compilerInterfaceClasspath
Resolution failed for 1 modules:
--------------------------------------------
  org.scala-sbt:compiler-interface:1.4.0-M1
        not found: /home/j00533938/.ivy2/local/org.scala-sbt/compiler-interface/1.4.0-M1/ivys/ivy.xml
        download error: Caught java.net.ConnectException: Connection timed out (Connection timed out) (Connection timed out (Connection timed out)) while downloading https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.4.0-M1/compiler-interface-1.4.0-M1.pom
        
        any insight as how to resolve this issue, much appreciated.
        
        Tks
        JO

**Comment by lihaoyi** [comment]
Can you post this in the chapter 2 thread? thanks!
