### ISSUE TITLE
testing with utest

### ISSUE THREAD

**Issue by anh977** [handsonscala/handsonscala#36]
I copied build.sc (2.18.scala) on page 31 of the book into a VSCode /mill setup.  I keep getting:
compiling 1 Scala source to /.../.../WorkSpaces/ScalaWS/HOS/chap2/out/mill-build/compile.dest/classes ...
[error] /.../.../WorkSpaces/ScalaWS/HOS/chap2/build.sc:8:23: not found: type Tests
[error]   object test extends Tests
[error]                       ^

Know what is wrong, everything works as long as I leave out the testing parts

**Comment by lihaoyi** [comment]
You're on a newer version of Mill that renamed `Tests` to `ScalaTests`
